### ISSUE TITLE
Validation fails if the attribute is not a standard string

### ISSUE THREAD

**Issue by daronco** [hallelujah/valid_email#22]
##### Context

My application has a custom strategy for devise to authenticate via LDAP. This strategy creates a User instance using the email provided by LDAP.

##### Problem

The user was always failing to be created with "Email is invalid", but if I tried to create the user manually it always succeeded. The email was valid.

After a while I found that the problem was that the email being set in the User model was not a standard ruby string object. It was a `Net::BER::BerIdentifiedString`, as returned by net-ldap.

##### Fix

I easily fixed it in the application converting the object to a string. The fact is that no other place in rails failed during the User validation, only the validation of the email using this gem that failed.

I'm creating this issue so you might consider treating this possible error in this gem. It can be easily fixed changing [this line](https://github.com/hallelujah/valid_email/blob/master/lib/valid_email/email_validator.rb#L10), that reads...

    m = Mail::Address.new(value)

...to something like...

    m = Mail::Address.new(value.to_s)

**Comment by chase439** [comment]
For anyone looking -- since it's a Net::BER::BerIdentifiedString, its encoding is usually ASCII-8BIT, you'll have to also change encoding:  `value.to_s.force_encoding("utf-8")` . Otherwise chaining it with `to_yaml` will produce a bad string, like when storing into a serialize Array.

**Comment by Fire-Dragon-DoL** [comment]
Should it be `value.to_s.encode("utf-8")` ? Otherwise you are changing the internal encoding, and string can become unreadable (or raise).

**Comment by chase439** [comment]
the `to_s` creates another instance of the string, so it's no impact. Regardless, here are the differences between `encode` and `force_encoding` -- [stackoverflow link](http://stackoverflow.com/questions/21614228/what-is-the-difference-betwee-encode-and-force-encoding-in-ruby)

**Comment by Fire-Dragon-DoL** [comment]
I know the difference and that's why I'm asking: we don't know the original string encoding

**Comment by chase439** [comment]
Gotcha, I think the encoding depends on the LDAP service people use. I just wanted to point out about the possible need of changing it.
