### ISSUE TITLE
Poorly configured legitimate domain mx validation fails

### ISSUE THREAD

**Issue by Epigene** [hallelujah/valid_email#66]
Got a user trying to register with email on `agb.lv` domain. I am doing an `mx_valid?` check, and it fails for this domain, even though the domain is legit.

```ruby
ValidateEmail.valid?('abc@agb.lv') #=> true
ValidateEmail.mx_valid?('abc@agb.lv') #=> false
ValidateEmail.mx_valid_with_fallback?('abc@agb.lv') #=> true
```

Google domain check here says the domain is poorly configured, but working.
https://toolbox.googleapps.com/apps/checkmx/check?domain=agb.lv

Should I be using `ValidateEmail.mx_valid_with_fallback?` to ensure these poorly configured domains pass?

**Comment by hallelujah** [comment]
Hi yes you should use it
