### ISSUE TITLE
ValidateEmail.valid?('email@randommail.com.') returns true

### ISSUE THREAD

**Issue by jchatel** [hallelujah/valid_email#72]
I'm using this gem with great success for my service for some times now and it works pretty well except a simple case that keeps coming back: adding a stupid character at the end

E.g.
ValidateEmail.valid?('email@randommail.com') -> true (correct)
ValidateEmail.valid?('email@randommail.') -> false (correct)
ValidateEmail.valid?('email@randommail.com.') -> true (INCORRECT)
ValidateEmail.valid?('email@randommail.com/') -> true (INCORRECT)

I don't want to use MX validation because this would consume way too much time, but I would think that this would be an easy check since ending by a dot or a slash is not conform (I get notified of errors when people try to send to those address).

**Comment by chitrank-samaiya** [comment]
+1 I am facing same issue

**Comment by mattecalcio** [comment]
Will using the domain validation option work?

`ValidateEmail.valid?('email@randommail.com.', domain: true)`

**Comment by Nghi93** [comment]
ValidateEmail.valid?('bla@bla.de+1256') -> true (INCORRECT)

**Comment by Nghi93** [comment]
The domain option works correctly. Also with the examples of op.

**Comment by Yaroslav-F** [comment]
Still rather convinced that `ValidateEmail.valid?('itsokay@site.com##')` should return `false` even if option `domain: true` is not passed.
Currently it returns `true` without a domain option and `false` with a domain option.

**Comment by hallelujah** [comment]
Closing as it is integrated in 0.1.0

Solution: Domain validation is enabled by default

**Comment by jchatel** [comment]
I did not upgrade to the new version yet, but looking at the code, shouldn't this return false on the old version? (the new version only set it to true by default)

ValidateEmail.valid?("email@randommail.com." , {:domain => true})
 => true

Or am I calling it wrong?

Rookie ruby question most likely but how is this going to use my params?

h1 = {:domain => true }
h2 = {:domain => false}
h1.merge(h2) #=> {:domain=>false}

def valid?(value, user_options={})
        options = {
          :mx => false,
         :domain => false,
         :message => nil
        }.merge(user_options)

shouldn't that be the opposite?

def valid?(value, user_options={})
        options = user_options.merge{
          :mx => false,
         :domain => false,
         :message => nil
        }

?
