### ISSUE TITLE
Does valid_email support procs as messages for errors

### ISSUE THREAD

**Issue by saadbinakhlaq** [hallelujah/valid_email#87]
Hey I am having some issues with internationalization of the messages here. I wanted to know if the error message supports procs.

I have a class like this 
```
require 'valid_email'

class CustomerValidator
  include ActiveModel::Validations

  ATTRIBUTES_LIST = %w(
    gender
    first_name
    last_name
    date_of_birth
    email
    street
    password
    password_confirmation
    postal_code
    country
    city
  ).map(&:to_sym).freeze

  attr_accessor(*ATTRIBUTES_LIST)

  validates :email, presence: true, email: { message: I18n.t('switch_reload.accounts.account_edit.please_valid_email') }

  def initialize(user_params = {})
    ATTRIBUTES_LIST.each do |attr|
      instance_variable_set(:"@#{attr}", user_params[attr])
    end
  end
end

```
But it is getting initialized with the default locale, and then for other locales it is still displaying messages from the default locale, is there a proc support for this. I have added this to the services directory in rails

**Comment by hallelujah** [comment]
Why not just using http://guides.rubyonrails.org/i18n.html#error-message-scopes instead of `:message`

**Comment by hallelujah** [comment]
Feel free to close or to discuss further.

Thanks for your contribution!
